modLoader = "javafml" #mandatory
license = "${mod_license}"
issueTrackerURL="https://github.com/Tejty/GameDiscs/issues"

[[mods]]
modId = "gamediscs"
version = "${mod_version}"
displayName = "${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

displayURL="https://www.curseforge.com/minecraft/mc-mods/game-discs"

#logoFile="gamediscs.png" #optional

#credits="Thanks for this example mod goes to Java" #optional

authors = "${mod_authors}" #optional


description = '''${mod_description}'''

[[dependencies.gamediscs]] #optional
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.gamediscs]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
